server:
  port: 1225
spring:
  application:
    name: notebook-service
  mvc:
    static-path-pattern: /**
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      default-zone: ${DISCOVERY_URL:http://eureka-server:8761}/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: debug
    org:
      springframework:
        cloud:
          sleuth:
            zipkin2:
              sender: debug
