server:
  port: 8765

spring:
  application:
    name: zuul-server
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    notebook:
      path: /**
      service-id: notebook-service

eureka:
  client:
    service-url:
      default-zone: ${DISCOVERY_URL:http://eureka-server:8761}/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: debug
    org:
      springframework:
        cloud:
          sleuth:
            zipkin2:
              sender: debug
